config/routes.rb
Rails.application.routes.draw do

  root 'employees#index'

  resources :employees

  resources :searches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	validates_presence_of :email
    validates_uniqueness_of :email, :case_sensitive => false, unless: -> {email.blank?}
    # validates_format_of :phone
    validates_format_of :date_of_birth, with: /\d{4}\/\d{2}\/\d{2}/
    validate :is_valid_dob?, unless: -> {date_of_birth.blank?}
    validates_presence_of :thumbnail_image_url, :big_image_url, :caption
    validates_format_of :thumbnail_image_url, :big_image_url, :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
end


  # def is_valid_dob?
  #     birthday = self.date_of_birth
  #     begin
  #       birthday.to_date
  #     rescue
  #       errors.add(:date_of_birth, "#{I18n.t 'api_c.dob_invalid'}")
  #     else
  #       if birthday > Date.today
  #         errors.add(:date_of_birth, "api_c.dob_future")
  #       elsif birthday < Date.today - 100.years
  #         errors.add(:date_of_birth, "api_c.dob_exceed")
  #       end
  #     end
  #   end

  # self.inheritance_column = "not_sti"

  #   def search_
  #       pokemon = Pokemon.all 

  #       pokemon = pokemon.where(['name LIKE ?', name]) if name.present?
  #       pokemon = pokemon.where(['type LIKE ?', type]) if type.present?
  #       pokemon = pokemon.where(['region LIKE ?', region]) if region.present?

  #       return pokemon
  #   end 

app/models/search.rb
class Search < ApplicationRecord
    self.inheritance_column = "not_sti"

    def search_employee
        employee = Employee.all 

        employee = employee.where(['name LIKE ?', name]) if name.present?
        # employee = employee.where(['type LIKE ?', type]) if type.present?
        # employee = employee.where(['region LIKE ?', region]) if region.present?

        return employee
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:employee_id, :employee_name, :employee_addresss, :email, :phone, :date_of_birth, :employee_image)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def show
        @search = Search.find(params[:id])
    end 

    def new 
        @search = Search.new
        # @types = Employee.distinct.pluck(:type)
        # @regions = Employee.distinct.pluck(:region)
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end 

    private

    def search_params
        params.require(:search).permit(:name)
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.number_field :employee_id %>
  </div>

  <div class="field">
    <%= form.label :employee_name %>
    <%= form.text_field :employee_name %>
  </div>

  <div class="field">
    <%= form.label :employee_addresss %>
    <%= form.text_field :employee_addresss %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :employee_image %>
    <%= form.text_area :employee_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_with(url: '/employees', method: 'get', local: true) do %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("Search") %>
<% end %>

<%= link_to "Advanced Search", new_search_path %>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Employee name</th>
      <th>Employee addresss</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Date of birth</th>
      <th>Employee image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_id %></td>
        <td><%= employee.employee_name %></td>
        <td><%= employee.employee_addresss %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.employee_image %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @post,renderer: BootstrapPagination::Rails %>
<br>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @employee.employee_id %>
</p>

<p>
  <strong>Employee name:</strong>
  <%= @employee.employee_name %>
</p>

<p>
  <strong>Employee addresss:</strong>
  <%= @employee.employee_addresss %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @employee.date_of_birth %>
</p>

<p>
  <strong>Employee image:</strong>
  <%= @employee.employee_image %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employees</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_with model: @search do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%#= f.label :type %>
    <%#= f.select :type, options_for_select(@types), include_blank: true %><br>

    <%#= f.label :region %>
    <%#= f.select :region, options_for_select(@regions), include_blank: true %><br><br>

    <%= f.submit "Search" %>
<% end %>

<p><%= link_to "Back", '/employees' %></p>

app/views/searches/show.html.erb
<h1>Search Results</h1>
<p><%= link_to "Back", new_search_path %></p>

<% if @search.search_pokemon.empty? %>
    <p>No Search were found.</p>
<% else %>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <!-- <th>Type</th>
                <th>Region</th> -->
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @search.search_employee.each do |employee| %>
            <tr>
                <td><%= employee.name %></td>
                <!-- <td><%#= employee.type %></td>
                <td><%#= employee.region %></td> -->
                <td><%= link_to 'Show', employee %></td>
                <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
                <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
</table>
<% end %>